### ISSUE TITLE
界面太丑了

### ISSUE THREAD

**Issue by ft9765581** [lidangzzz/hedgehog-lab#13]
安利小党党 element ui ，改善用户体验，直接复制业务代码就行，非常简单

**Comment by lidangzzz** [comment]
好

**Comment by yuhengshen** [comment]
不需要太好看的UI，比较有学术感。:smile:

**Comment by AGDholo** [comment]
推荐 vuetify

**Comment by lidangzzz** [comment]
vuetify是啥，我不会用vue，让我学用react已经很困难了。。。

**Comment by AGDholo** [comment]
vuetify 和 element 一样，也是 vue 的 ui 库，但是看你源码都和 react 耦合在一起，也装上了 material-ui，用 material-ui 也不错
虽然 vue 比 react 简单很多，但是这源码要换费劲

**Comment by lidangzzz** [comment]
@AGDholo 好的，您能帮我修改一下GUI吗？我希望整个code editor、compile&run按钮、tutorials在左半边，results和整个react渲染出来的list of TeX和plotlyjs在右半边，不知道您有啥办法没有，我试了试发现都失败了

**Comment by AGDholo** [comment]
@lidangzzz 
我正在看源码，我有几个问题：
1. 为什么装了这么多前端库？material-ui，bootstrap，semantic-ui，都是必须要用到的吗？
2. 为什么 ts 的类型会用 .js 文件来做，我没有怎么写过 ts，我的 vscode 上一直报错（项目能够正常运行，编辑器会报错），提示类型注释只能在 TypeScript 文件中使用。我应该怎么解决编辑器报错的问题？
3. 项目中同时存在 yarn.lock 和 package-lock.json，看起来是开发过程中使用了两种包管理工具，可能需要移除一种并进行统一管理。

我已经做好了的：
> 我希望整个code editor、compile&run按钮、tutorials在左半边，results和整个react渲染出来的list of TeX和plotlyjs在右半边。

我已经将布局修改成左右两边并提供响应式的方案，并且针对大屏设备增加了左右边距，results 放在了右边，不过我不明白 list of TeX 和 plotlyjs 是哪个组件？
效果图：https://wx1.sbimg.cn/2020/07/16/CUBT7.png

我目前打算做的：
1. 如果您愿意的话，我可以将整个站点使用 material-ui 编写来提供更美观的布局，我会先提供预览站点，然后进行讨论。

**Comment by AGDholo** [comment]
我用 material-ui 稍微优化了一下网站样式 #17 
效果图：https://wx2.sbimg.cn/2020/07/16/CUqKh.png

**Comment by Leo-Mu** [comment]
> 我用 material-ui 稍微优化了一下网站样式 #17
> 效果图：https://wx2.sbimg.cn/2020/07/16/CUWJG.png

Amazing，快提一个 PR 吧

**Comment by AGDholo** [comment]
@Leo-Mu 最新的 pr 就是这个

**Comment by lidangzzz** [comment]
@AGDholo 爸爸！！！！！！我爱你！！！！！！！！！
