### ISSUE TITLE
LaTex render breaks when switching between examples

### ISSUE THREAD

**Issue by xplorld** [lidangzzz/hedgehog-lab#15]
Reproduction:

1. click "Tutorial 5: TeX in Hedgehog Lab"
2. click "compile & run"
3. click "Tutorial 7: Symbolic computing"
4. click "compile & run"

Expected result: LaTex lines of f(x), f'(x) and blabla
Actual result: Only one line of f'(x)

Walkaround: refresh, skip step 1 and 2, would work as expected.

**Comment by xplorld** [comment]
Can' t reproduce after 1 hour. Maybe some mysterious flakyness. Closing.

**Comment by lidangzzz** [comment]
I also noticed the similar issue....let me know if anyone could have a certain way to replicate. Thanks for feedback.
