### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by boydc2014** [lidangzzz/hedgehog-lab#18]
1. Please consider separate client and runtime or any other libs into isolated packages, they should have there own build\test process. [Yarn workspace](https://classic.yarnpkg.com/en/docs/workspaces/) is highly recommended.

2. Please consider use [Manaco editor](https://microsoft.github.io/monaco-editor/) as the code editor, which is the same editor that powers VSCode. (I didn't check the code see if you are using it or not, if you already use it, please ignore this one)

3. Create a issue template, to help make issues more organized.

**Comment by hepesu** [comment]
Manaco editor + 1

**Comment by lidangzzz** [comment]
Thanks for your feedback. @hepesu @hepesu 

1. Yes it's a good idea and it's quite straight forward to extract "hedgehog runtime" and all libraries from this project and package as a "interpreter". If anybody is interested in a standalone runtime in other projects, I will be happy to provide support in that way. 

2. I've replaced the default code editor with Monaco Editor. Unfortunately it doesn't work well on my Android Chrome and iPad Chrome. I'm thinking about to replace it with React Ace. What do you think?

3. Yes it's a good idea I will do that.

**Comment by lidangzzz** [comment]
@boydc2014  sorry I forgot to mention the right ID. Please check my latest comment. Thanks

**Comment by AGDholo** [comment]
- [ ] Yarn workspace is under discussion
- [x] Manaco editor 
- [x] Issue template

**Comment by boydc2014** [comment]
> @boydc2014 sorry I forgot to mention the right ID. Please check my latest comment. Thanks

Sorry for the late response. Get lost in bunch of notifications. 

Glad to see the split of runtime and editing, and manioc editor enabled. 

To your "react-ace" suggestion, maybe you already figured it out, but my suggestion is simply no. Or only switch to react-ace in a environment that don't work well with Manaco. Because the reason for Manaco is not for some simple line number display, highlighting, line-wrap, all that traditional editing feature, but more for the language-server support, which will enable you do a much better, validation, suggestion, code snippet, auto-complete, all on top of your specific language context.
