### ISSUE TITLE
暗黑模式支持（未完成）

### ISSUE THREAD

**Issue by AGDholo** [lidangzzz/hedgehog-lab#25]
我实现了暗黑模式的主题，但是存在以下几点问题：
1, 并未做切换主题功能，不会用 react hooks，需要大佬们帮忙补充功能。
2. 渲染图表的颜色是写死在 `hedgehog-lab\src\core\runtime.js` 里面的，无法动态的做主题切换。

主题设置可在 `App.js` 中查看，动态切换主题只需要往 `type` 里面塞变量就行。

预览图：![image](https://user-images.githubusercontent.com/13300332/87846923-528a3f00-c906-11ea-8393-f71f2d075783.png)

**Comment by lidangzzz** [comment]
好，gkd

**Comment by lidangzzz** [comment]
react hooks是啥= =

**Comment by cbian03** [comment]
我不太清楚你指的是什么. 不过我查了一下doc, material UI的theme hook是用 useTheme, 利用context实现的. 等立党merge吧.
```js
import React from 'react';
import { useTheme } from '@material-ui/core/styles';

export default function MyComponent() {
 // 这里的theme是由ThemeProvider传入的
  const theme = useTheme();

  return <div>{`spacing ${theme.spacing}`}</div>;
}
```

**Comment by AGDholo** [comment]
@cbian03 之前是用的 class component，里面用不了 hooks，现在都改为了 pure function，hooks 就可以直接拿来用了。
暗黑模式可能要搁置一下，正在考虑把布局搞成三栏的样式。
