### ISSUE TITLE
Suggestion to refine the webpage

### ISSUE THREAD

**Issue by tabVersion** [lidangzzz/hedgehog-lab#29]
**Is your feature request related to a problem? Please describe.**
The page cannot slide up and down when my mouse is in the code region.

**Describe the solution you'd like**
Put tutorials and links on the left side of the page, which do not move when the page sliding up and down.

**Another suggestion**
Use a badge to wrap the `follow twitter link` and `fork repo link`. 

For example, ![tweet](https://img.shields.io/twitter/url?url=https%3A%2F%2Ftwitter.com%2Flidangzzz) and ![fork](https://img.shields.io/github/forks/lidangzzz/hedgehog-lab)

**Comment by lidangzzz** [comment]
好，我一直想弄这个，可是不会搞= =

**Comment by tanjiarui15** [comment]
> 好，我一直想弄这个，可是不会搞= =

https://shields.io/category/social

**Comment by AGDholo** [comment]
In plan, Waiting for the refactoring of the page. After the PR merges, I will write it. The currently planned style can be referred to #25 

I create three columns, where the leftmost tutorials can be fixed

**Comment by AGDholo** [comment]
ref #39

**Comment by AGDholo** [comment]
Most of the functionality is complete
ref #45
