### ISSUE TITLE
Use ts (or tsx) extension for .js files with type annotations (or tsx syntax)

### ISSUE THREAD

**Issue by CXuesong** [lidangzzz/hedgehog-lab#30]
**Is your feature request related to a problem? Please describe.**
There has been a lot of TypeScript (or JSX) snippets in scattered in the JS files in the project.

**Describe the solution you'd like**
Use appropriate extension names for the "js" files so other toolchain (like tsc) can handle it properly.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lidangzzz** [comment]
Thanks for your feedback. Will fix later.  -lidang

**Comment by AGDholo** [comment]
ref #19
