### ISSUE TITLE
Prefetch and loading Script via URL parameter 

### ISSUE THREAD

**Issue by lidangzzz** [lidangzzz/hedgehog-lab#42]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Prefetch and loading Script via URL parameter.

A potential design of this feature will be like:

http://hedgehog-lab.github.io/?auto_run=[TRUE OR FALSE]&your_url=[YOUR_ENCODED_URL]

in which the script will be running automatically when auto_run is set to true, and with a URL of hedgehog script (on Github): https://gist.githubusercontent.com/lidangzzz/2adebd6a771f50e6430a34ec61d928af/raw/1f9add39370b00dfbb3f5d20c8bc203dd09f52c2/my_first_notebook.hss

And user can generate a link to share with teammates/students/collegues in this format:
http://hedgehog-lab.github.io/?auto_run=true&your_url=https%3A%2F%2Fgist.githubusercontent.com%2Flidangzzz%2F2adebd6a771f50e6430a34ec61d928af%2Fraw%2F1f9add39370b00dfbb3f5d20c8bc203dd09f52c2%2Fmy_first_notebook.hss

which allow them to click the URL and execute the whole script immediately, or even embed an <iframe> into personal website or project page with a full demo of code and execution results.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by AGDholo** [comment]
ref #71
