### ISSUE TITLE
GPU的选择问题

### ISSUE THREAD

**Issue by RenPxyz** [lidangzzz/hedgehog-lab#49]
你好，我的笔记本有两个显卡，一个是AMD自带的核显，另外一个是Nvdia的1650ti，每次计算的时候都是调用AMD核显进行计算的，请问怎么才能调用1650ti来计算？
使用AMD核显的一个主要问题是会卡顿，当计算 2000-by-2000 matrix相乘时候，AMD核显占用会到100%，会造成界面卡顿，让人很难受，能否把计算切换到独立显卡上吗

**Comment by lidangzzz** [comment]
这个你要自己在操作系统里设置

**Comment by RenPxyz** [comment]
> 这个你要自己在操作系统里设置

我试了一下，用英伟达的设置面板可以选择独显，但是当矩阵计算量比较大的时候，AMD的核显有一瞬间会占用100%，从而导致黑屏大概1s，不知道是什么原因，可能核显余独显之间的调度任然有问题。

**Comment by RenPxyz** [comment]
> 这个你要自己在操作系统里设置
而且黑屏之后就不能再次计算了，一运行就会报错：Error: TypeError: Failed to execute 'shaderSource' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLShader'.

**Comment by lidangzzz** [comment]
证明你显存不够，而且你也没设置成功，你自己再鼓捣鼓捣吧，你nvidia的GPU占用率没上去就证明设置是完全错的，另外2000*2000的矩阵大概率比你显存要大
