### ISSUE TITLE
How can I add label <help wanted>?

### ISSUE THREAD

**Issue by Haise-Turquoise** [lidangzzz/hedgehog-lab#58]
Some one told me this need repo permission. 
1-Does that mean I need to apply to administrator of this project to add the label?
2-Who have the permission to add label to issue? Anyone or administrator?

**Comment by AGDholo** [comment]
1. Actually you need the write access permission: https://docs.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests
2. The author of the project and anyone with this permission (requires author assignment)
